### PR TITLE
Remove tuning

### PR DESCRIPTION
**Pull request by timokau**
## Description

Done on top of #145 to avoid conflicts. First step in #146. I wanted to get feedback on this first step first before I go all in and remove the `Tunable` class. An alternative would be to rewrite the functionality with the scikit-learn APIs instead of the custom `Tunable`, but I would argue that the tuning functionality does not belong into the library in the first place. There are libraries dedicated to that, and the user can choose one to their liking. Adhering to the scikit-learn API should make that relatively straightforward.

What do you think @kiudee?

## Motivation and Context

Simplification & removal of technical debt.

## How Has This Been Tested?

Linters, test suite.

## Does this close/impact existing issues?

Impacts #146. Eases the further steps for #94.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly. (by removing the relevant sections)
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kiudee** [comment]
I completely agree that the tuning part should be handled by other libraries. There is nothing specific to this library, which would require its own tuning implementation.

So removing Tunable and using the scikit-learn interface is the way to go.

**Comment by timokau** [comment]
Done. This is ready for review in principle, though it depends on #145.

-2k lines, roughly 10% of the code base :tada:

**Comment by timokau** [comment]
Also added some changelog entries.

**Comment by timokau** [comment]
Rebased now that https://github.com/kiudee/cs-ranking/pull/145 is merged.

**Pull request merged**
