### PR TITLE
Add CONTRIBUTING documentation

### LINKED ISSUE #89: Document the release process
We are using `bump2version` now to change the version number and create a tagged commit. This triggers an upload of the new version to PyPi.
At the same time the `HISTORY.rst` file needs to be updated with the recent changes.

This process should be documented in Sphinx.

The correct order is:

1. Update `HISTORY.rst` and commit.
2. Run `bump2version [patch|minor|major]`
3. Push commits and tag to master/branch.

### PR DESCRIPTION
**Pull request by timokau**
## Description

Fixes #89. Roughly based on https://github.com/kiudee/bayes-skopt/blob/master/CONTRIBUTING.rst. This is taking some time because I have to learn re-structured text basics first.

## Motivation and Context

We want to move from being mostly an internal project to being a public library. Documentation is essential for that.

## Does this close/impact existing issues?

Fixes #89.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by timokau** [comment]
This is ready for review now. Here's a [rendered](https://github.com/kiudee/cs-ranking/blob/1e9912967457236b6f5d8ac11a01bb09ffaba4cb/CONTRIBUTING.rst) version.

**Comment by kiudee** [comment]
I think we can directly include it in our documentation:
https://github.com/kiudee/cs-ranking/blob/master/docs/index.rst

**Comment by timokau** [comment]
Done. I would have preferred to have it as a subsection of "introduction", but  I couldn't figure out how to include it at the right hierarchical position. Maybe it works better as its own chapter later in the docs anyway. Contributing probably should come after usage.

**Comment by timokau** [comment]
I don't know why, but for some reason github said this wasn't mergeable. I rebased on current master (no conflicts), so it should work now. No changes since you approved.

**Pull request merged**
