### PR TITLE
Move logger initialization to the module level

### PR DESCRIPTION
**Pull request by timokau**
## Description

This is what is usually recommended in python logging tutorials
(including the official documentation). It also frees us up from having
the "logging" attribute in our estimators, which the scikit-learn check
doesn't like (although it doesn't really hurt in this case, since a
logger hardly counts as state).

## Motivation and Context

Following standard practices and making progress on the "no_attributes_set_in_init" check of the scikit-learn estimator check suite.

## How Has This Been Tested?

Testsuite and pre-commit.

## Does this close/impact existing issues?

Impacts #94, #116.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by timokau** [comment]
@kiudee the travis failures here are very confusing to me. I think they are due to a cached python38 miniconda env. Could you [clear the travis caches](https://docs.travis-ci.com/user/caching/#clearing-caches)?

**Comment by kiudee** [comment]
I removed all caches and restarted the builds.
I will soon setup a pyproject.toml, which should help us clean up all that dependency setup on travis.

**Comment by timokau** [comment]
Travis is still unhappy for some reason (one more thread on it: https://travis-ci.community/t/expected-waiting-for-status-to-be-reported-is-back/7550/7). Maybe #156 will help, otherwise we might just move to GH actions. Either way, probably safe to ignore here.

**Comment by kiudee** [comment]
I think the reason is that I can only restart the build of the pull request in the travis-ci dashboard.
Can you try triggering a rebuild of the branch using:
```bash
git commit --allow-empty -m "Trigger"
```

**Comment by timokau** [comment]
I don't think that is it, I have seen this issue multiple times already when trying to work around the caches issue. I'll try again though.

**Comment by timokau** [comment]
So this just resurrected the other error again :smile: Do you plan to finish #110 near term? Or should I look into it? Its probably better to focus on that instead of patching up the current solution.

**Comment by kiudee** [comment]
Yes, I made some progress on the travis-tox integration in conjunction with our parallel tests. I will push a first version for discussion soon.

**Comment by timokau** [comment]
In that case I propose to ignore the travis issue for now. I have removed the trigger commit again.

**Review by kiudee — APPROVED** [review]

**Pull request merged**
