### PR TITLE
Remove usage of Imputer

### PR DESCRIPTION
**Pull request by timokau**
## Description

Imputer was removed from preprocessing in
https://github.com/scikit-learn/scikit-learn/pull/13796. To be
compatible with newer scikit-learn versions, we need to stop using it.
impute.SimpleImputer seems to be a viable replacement.

This caused failures on travis.

## Motivation and Context
The latest sklearn caused failures on travis.

## How Has This Been Tested?

Ran all tests with sklearn 0.22.

## Does this close/impact existing issues?

Impacts https://github.com/kiudee/cs-ranking/pull/65, where the CI fails because of this.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by timokau** [comment]
The remaining travis failures look like they might be related to the [recent pymc 3.8 release](https://github.com/pymc-devs/pymc3/releases), however I cannot reproduce them locally with pymc 3.8. I'll continue to look into this.

**Comment by timokau** [comment]
Not sure why I couldn't initially reproduce this. pymc 3.8 is responsible. To be more specific, git-bisect shows that https://github.com/pymc-devs/pymc3/commit/521174cfb52a4dfe7b8bd28b1ce193df58e9dd40 introduced the issue.

**Comment by timokau** [comment]
Now there's a segfault. Weird that all these issues turn up at the same time.

**Comment by srinikrish22** [comment]
Replacing the import with an alternative Imputer function fixes the issue. Please check my commit 7a2cf9e24723eeed761642a3478e5a4a9973f96f

**Comment by timokau** [comment]
Is this in any way different from what I did here?

**Comment by srinikrish22** [comment]
Doesn't seem a lot different. Essentially the change I made is a subset of yours. For me the builds didn't have the same issue after just changes to the imports though.

**Comment by timokau** [comment]
The other issues were unrelated to the Imputer change. They just happened to show up in this PR because travis updated some of its dependencies.

**Comment by srinikrish22** [comment]
Well then I guess it is the same :)

**Comment by timokau** [comment]
Okay, I'm fine with that being merged in the other PR :) If the other travis issues vanished by themselves (maybe further dependency updates? We should really have a reproducible environment there.), even better.

**Comment by prithagupta** [comment]
https://github.com/pymc-devs/pymc3/issues/3735

**Comment by kiudee** [comment]
@prithagupta good find. I deleted the caches and restarted the build. Let’s see…

**Comment by prithagupta** [comment]
Another issue which talks about the same problem in detail:
https://github.com/nedbat/coveragepy/issues/883

**Comment by kiudee** [comment]
I managed to find a fix for the issue. It is implemented in my branch [kiudee:replace-imputer-usage](https://github.com/kiudee/cs-ranking/tree/replace-imputer-usage). Try pulling the changes.

**Pull request closed without merging**
