### PR TITLE
Lint python code with flake8

### PR DESCRIPTION
**Pull request by timokau**
## Description

"flake8 is a python tool that glues together pep8, pyflakes, mccabe, and
third-party plugins to check the style and quality of some python code."

Flake8 is reporting a lot of issues to fix. I think its best to get the
checks in first and then gradually tighten the checks as we fix the
outstanding issues.

## Motivation and Context

Following more of python's best practices.

## How Has This Been Tested?

Ran `flake8`, travis is tested in this PR.

## Does this close/impact existing issues?

#104 (not closed though,  we should keep it open until we have weeded out the remaining issues).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by timokau** [comment]
One potential downside is that `flake8` is a tad slow (~7s for our repo on my machine). I think its worth it though.

**Comment by timokau** [comment]
Also `pre-commit` will take care of running it only on the changed files, so it shouldn't be much of an issue.

**Comment by kiudee** [comment]
> 
> 
>One potential downside is that flake8 is a tad slow (~7s for our repo on my machine). I think its worth it though.

That appears to be a reasonable runtime for the benefit.


> Also `pre-commit` will take care of running it only on the changed files, so it shouldn't be much of an issue.

Oh, that’s good to know. Then it also should not be that noticable, when interacting with git.

**Comment by timokau** [comment]
Done in https://github.com/kiudee/cs-ranking/issues/104#issuecomment-605891281. This needs re-approval, since I removed the test commit.

**Pull request merged**
