### PR TITLE
Properly pass on fit kwargs to the core network

### LINKED ISSUE #126: FATE Choice ignores parameters of the fit method
The fit method parameters are:

https://github.com/kiudee/cs-ranking/blob/49e39df3257679acb157b4ca0f47a8bfaa73866a/csrank/choicefunction/fate_choice.py#L134-L150

However the parameters are not passed to the super class:

https://github.com/kiudee/cs-ranking/blob/49e39df3257679acb157b4ca0f47a8bfaa73866a/csrank/choicefunction/fate_choice.py#L199

https://github.com/kiudee/cs-ranking/blob/49e39df3257679acb157b4ca0f47a8bfaa73866a/csrank/choicefunction/fate_choice.py#L208

### PR DESCRIPTION
**Pull request by timokau**
## Description

Previously we were passing on **kwargs, but also specifying some
arguments explicitly which meant they were not included in **kwargs and
not passed on.

To make this more maintainable, we now also delegate the documentation
to the core.

## Motivation and Context

#126 

## Does this close/impact existing issues?

Fixes #126

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by timokau** [comment]
This fixes #126, but I'll check if there are more instances of this issue on our other estimators (I suspect there will be).

**Comment by timokau** [comment]
I have found no other obvious cases of this. Its very hard to screen for though. At some point we should add some more extensive static analysis, like `pylint`'s "unused variable" which would have caught this.

Tests & pre-commit hooks pass. Test had to be adapted, since the test parameters (100 instead of 35 epochs, no validation split instead of 10%) are now actually respected.

While looking at the implementation and the test I also noticed that we are inconsistent in the typing of `verbose`. Sometimes we pass ints, sometimes booleans. We should think about introducing `mypy` typing.

Ready for review.

**Comment by timokau** [comment]
The alternative would be to branch off `1.1` at the point of the `1.1` tag, cherry-pick this commit and release `1.1.1`. That would also be fine by me, just slightly more work.

**Comment by kiudee** [comment]
Yes, the problem is that currently we only deploy tags on master. We would need something like [conditional deployment](https://docs.travis-ci.com/user/deployment#conditional-releases-with-on) such that it will also work for branches.

In any case, the code seems stable enough to go to 1.2.0.

**Comment by timokau** [comment]
We probably need to look into this at some point anyway, but maybe not yet.

**Pull request merged**
